version: "3"

services:
  index:
    build:
      context: .
      dockerfile: ./docker/index/Dockerfile
    restart: always
    volumes:
      - ./config:/www/index/config
      - ./logs:/www/logs
    privileged: true
    networks:
      - bnb48
    links:
      - mysql
    depends_on:
      - mysql

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    restart: always
    ports:
      - "0.0.0.0:8888:8888"
    volumes:
      - ./config:/www/api/config
      - ./logs:/www/logs
    privileged: true
    networks:
      - bnb48
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: "mysql:8.0.29"
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpasswd
      MYSQL_ROOT_HOST: "%"
    restart: always
    command: ["--default-authentication-plugin", "mysql_native_password"]
    ports:
      - "0.0.0.0:32089:3306"
    networks:
      - bnb48
    volumes:
      - /etc/localtime:/etc/localtime
      - ../data/bnb48_index/mysql/conf:/etc/mysql/conf.d
      - ../data/bnb48_index/mysql/data:/var/lib/mysql
      - ../data/bnb48_index/mysql/logs:/var/log/mysql
      - ./scripts/sql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

networks:
  bnb48:
    driver: bridge
