fans_index:
    name: fans_index
    port: 8888
    route_prefix: /fans_index


log:
    dir: /www/fans_index/logs
    level: info
    max_size: 1000 #mb
    max_backups: 100
    max_age: 60 # days
    compress: false

mysql:
    url: root:mysqlpasswd@tcp(mysql:3306)/fans_index?charset=utf8mb4&parseTime=True&loc=Local
#    url: root:mysqlpasswd@tcp(44.197.228.58:32089)/fans_index?charset=utf8mb4&parseTime=True&loc=Local
    prefix: ""
    max_idle_conns: 10
    max_open_conns: 50
    conn_max_lifetime: 60
    slow_threshold: 3
